spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_AUTH}
    username: ${SPRING_DATASOURCE_USERNAME_AUTH}
    password: ${SPRING_DATASOURCE_PASSWORD_AUTH}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${AUTH_DB_DDL_AUTO:create}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true