version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_MULTIPLE_DATABASES: auth_db,user_db
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - livo-network

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    volumes:
      - pgadmindata-dev:/var/lib/pgadmin/data
    depends_on:
      - postgres
    networks:
      - livo-network
  
  #Aplication Eureka and Gateway
  discovery-server:
    build: 
      context: ../discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - livo-network

  api-gateway:
    build: 
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    networks:
      - livo-network

networks:
  livo-network:
    driver: bridge

volumes:
  pgdata-dev:
    driver: local
  pgadmindata-dev:
    driver: local
